<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Roku Smart TV 2025 – 32-Inch Select Series, 1080p Full HD TV',
                'slug' =>'Rokudfdg',
                'short_description' => '32-Inch Full HD Smart TV',
                'description' => 'Roku Smart TV 2025 with 1080p Full HD resolution and smart features.',
                'regular_price' => 116,
                'sale_price' => null,
                'warehouse_price' => 100,
                'quantity' => 20,
                'brand_id' => 1,
                'category_id' => 1,
                'featured' => 1,
                'image' => 'product-4.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Xiaomi 108 cm (43 inch) FX Pro QLED Ultra HD',
                'slug' =>'Xiaomiqed',
                'short_description' => '43-Inch QLED Ultra HD TV',
                'description' => 'Xiaomi 43-inch FX Pro QLED Ultra HD smart TV with vivid colors.',
                'regular_price' => 500,
                'sale_price' => null,
                'warehouse_price' => 450,
                'quantity' => 15,
                'brand_id' => 2,
                'category_id' => 1,
                'featured' => 1,
                'image' => 'product-5.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Xiaomi 138 cm (55 inch) FX Ultra HD 4K',
                'slug' =>'Xiaomifdsfsd',
                'short_description' => '55-Inch Ultra HD 4K TV',
                'description' => 'Xiaomi FX 55-inch Ultra HD 4K smart TV with immersive viewing.',
                'regular_price' => 400,
                'sale_price' => null,
                'warehouse_price' => 350,
                'quantity' => 18,
                'brand_id' => 2,
                'category_id' => 1,
                'featured' => 1,
                'image' => 'product-6.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Panasonic 80 cm (32 inches) HD Ready Smart LED',
                'slug' =>'Panasotegs',
                'short_description' => '32-Inch HD Ready Smart LED',
                'description' => 'Panasonic Smart LED TV with HD Ready resolution.',
                'regular_price' => 250,
                'sale_price' => 129,
                'warehouse_price' => 200,
                'quantity' => 12,
                'brand_id' => 3,
                'category_id' => 1,
                'featured' => 1,
                'image' => 'product-7.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JBL Tune 770NC - Adaptive Noise Cancelling',
                'slug' =>'JBLsfgbTu',
                'short_description' => 'Noise Cancelling Headphones',
                'description' => 'JBL Tune 770NC headphones with adaptive noise cancelling technology.',
                'regular_price' => 100,
                'sale_price' => null,
                'warehouse_price' => 80,
                'quantity' => 30,
                'brand_id' => 4,
                'category_id' => 2,
                'featured' => 1,
                'image' => 'product-8.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HLDIRECT 47 Inch Gaming Desk with LED Lights, Large RGB Computer',
                'slug' =>'HLDIRsxE',
                'short_description' => '47-Inch Gaming Desk with LED',
                'description' => 'Large RGB gaming desk with LED lights for immersive gaming experience.',
                'regular_price' => 179,
                'sale_price' => null,
                'warehouse_price' => 150,
                'quantity' => 25,
                'brand_id' => 5,
                'category_id' => 3,
                'featured' => 1,
                'image' => 'product-9.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lufeiya L Shaped Computer Desk with Power Outlet Shelves, 47 Inch Corner Desk',
                'slug' =>'Lufeisdcy',
                'short_description' => 'L Shaped Computer Desk',
                'description' => 'Space-saving L-shaped computer desk with built-in power outlet shelves.',
                'regular_price' => 65,
                'sale_price' => null,
                'warehouse_price' => 50,
                'quantity' => 40,
                'brand_id' => 5,
                'category_id' => 3,
                'featured' => 1,
                'image' => 'product-10.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laptop Stand for Desk, Adjustable Laptop Riser ABS+Silicone',
                'slug' =>'Laptopuwyed',
                'short_description' => 'Adjustable Laptop Stand',
                'description' => 'Adjustable laptop riser made from ABS+Silicone for ergonomic use.',
                'regular_price' => 9,
                'sale_price' => null,
                'warehouse_price' => 7,
                'quantity' => 50,
                'brand_id' => 6,
                'category_id' => 4,
                'featured' => 1,
                'image' => 'product-11.jpg',
                'images' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
    }
}
